# Generated by Django 3.0.5 on 2020-04-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
        ('accounts', '0002_auto_20200427_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('post', 'Post'), ('follow', 'Follow'), ('like', 'Like'), ('mention_post', 'Mention Post'), ('mention_comment', 'Mention Comment'), ('new con', 'New Con'), ('invite', 'Invite'), ('change_admin', 'Change Admin'), ('recommend', 'Recommend'), ('add_grp_member', 'Add Group Member'), ('favourites', 'Favourites'), ('comment', 'Comment'), ('shared_your_post', 'Shared Your Post'), ('share', 'Share'), ('tag', 'Tag')], default='post', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserGroup')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomended_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
